apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-result-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
      - name: result-service
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
          - name: REDIS_HOST
            value: "{{ .Release.Name }}-redis"